/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AhnBasitUnit6Assignment;

import java.awt.Color;

/**
 *
 * @author mubas
 */
public class Menu extends javax.swing.JFrame {

    private StudyPoints studyWindow;

    /**
     * Creates new form Unit6Assignment
     */
    public Menu() {
        initComponents();
        getContentPane().setBackground(Color.CYAN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnStudyPoints = new javax.swing.JButton();
        btnMCQuiz = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(575, 435));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel1.setText("Software Development Life Cycle Studying Program");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        btnStudyPoints.setText("Study Points");
        btnStudyPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudyPointsActionPerformed(evt);
            }
        });
        getContentPane().add(btnStudyPoints, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 240, 70));

        btnMCQuiz.setText("MC Quiz");
        btnMCQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMCQuizActionPerformed(evt);
            }
        });
        getContentPane().add(btnMCQuiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 240, 70));

        btnExit.setText("Exit");
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 240, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudyPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudyPointsActionPerformed
        if (studyWindow == null) {
            studyWindow = new StudyPoints(this);

        }

        studyWindow.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnStudyPointsActionPerformed

    private void btnMCQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMCQuizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMCQuizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMCQuiz;
    private javax.swing.JButton btnStudyPoints;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
